### ISSUE TITLE
[BUG]: Vertex AI blogpost is outdated after 0.20.0 release

### ISSUE THREAD

**Issue by francobocciDH** [zenml-io/zenml#1001]
### Contact Details [Optional]

francogbocci@gmail.com

### System Information

ZenML version: 0.20.5
Install path: /Users/f.bocci/Library/Caches/pypoetry/virtualenvs/banana-bMSm4ime-py3.9/lib/python3.9/site-packages/zenml
Python version: 3.9.6
Platform information: {'os': 'mac', 'mac_version': '10.15.7'}
Environment: native
Integrations: ['gcp', 'graphviz', 'kubeflow', 'kubernetes', 'scipy', 'sklearn']

### What happened?

Trying to follow the [guide to run a pipeline using Vertex AI](https://blog.zenml.io/vertex-ai-blog/), it fails because ZenML does not now have a `metadata-store` stack category.

```shell
$ zenml
Stack Components:
      alerter                 Commands to interact with alerters.
      annotator               Commands to interact with annotators.
      artifact-store          Commands to interact with artifact stores.
      container-registry      Commands to interact with container registries.
      data-validator          Commands to interact with data validators.
      experiment-tracker      Commands to interact with experiment trackers.
      feature-store           Commands to interact with feature stores.
      model-deployer          Commands to interact with model deployers.
      orchestrator            Commands to interact with orchestrators.
      secrets-manager         Commands to interact with secrets managers.
      step-operator           Commands to interact with step operators.
$ zenml metadata-store
Error: No such command 'metadata-store'.
```

### Reproduction steps

1. zenml metadata-store

If I don't add it and run the Vertex AI pipeline, it fails.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by htahir1** [comment]
@francobocciDH Thanks for reporting the issue. We have recently undergone a [big architectural shift](https://blog.zenml.io/zenml-revamped/) and therefore a lot of the blog is a bit outdated! In particular, the metadata store is no longer a required stack component.

In order to make the vertex orchestrator work, I would suggest either taking a look at the [updated docs page](https://docs.zenml.io/component-gallery/orchestrators/gcloud-vertexai), or taking a look at the [migration guide](https://docs.zenml.io/guidelines/migration-zero-twenty) that will help you update that blog's code to  the 0.20.5 world.

**Comment by francobocciDH** [comment]
Hey! Thanks for the quick reply. I followed the updated docs page at first. When launching the pipeline, I'm getting an error that I assume it's due to a non migrating component:
```
Connection refused'))
object at 0x7fb560c1ab50>: Failed to establish a new connection: [Errno 111] 
/api/v1/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection 
HTTPConnectionPool(host='127.0.0.1', port=8237): Max retries exceeded with url
RuntimeError: Error initializing rest store with URL 'http://127.0.0.1:8237':
│ /usr/local/lib/python3.9/site-packages/zenml/zen_stores/base_zen_store.py:10 │
```
(I'm sorry about the format of the log, Cloud logging provides them like this :( )

In case it's useful, this is the config I'm using:
```
schedule:
  catchup: false
  cron_expression: 30 9 * * *
  start_time: 2022-10-01T09:30:00
settings:
  docker:
    replicate_local_python_environment: poetry_export
    apt_packages: [git]
    required_integrations: [gcp]
  resources:
    cpu_count: 1
    memory: "1GB"
steps:
  importer:
    enable_cache: true
  trainer:
    enable_cache: false
    parameters: {}
    settings:
      resources:
        cpu_count: 1
        memory: "2GB"
  evaluator:
    enable_cache: true

```
