### ISSUE TITLE
[BUG]: Stack with ID <UUID> not found

### ISSUE THREAD

**Issue by wefner** [zenml-io/zenml#1043]
### System Information

ZenML version: 0.21.0
Install path: /usr/local/lib/python3.9/site-packages/zenml
Python version: 3.9.15
Platform information: {'os': 'linux', 'linux_distro': 'debian', 'linux_distro_like': '', 'linux_distro_version': '10'}
Environment: docker
Integrations: ['aws', 'kubeflow', 'kubernetes', 's3', 'scipy']

--- 
Also observed with 0.20.5.

### What happened?

When running a pipeline with a Kubeflow or Kubernetes stack, it fails on the first pipeline step with 

```
KeyError: 'Stack with ID 710732b7-2946-48ce-a484-b3baa3af1cbf not found.'
```

This stack ID is the one I have locally, not sure why it needs it in the step.

### Reproduction steps

1. Create/Import Kubernetes/Kubeflow stack. As an example, this stack

```
components:
  artifact_store:
    configuration:
      authentication_secret: null
      client_kwargs: null
      config_kwargs: null
      key: null
      path: s3://my_bucket
      s3_additional_kwargs: null
      secret: null
      token: null
    flavor: s3
    id: 5cbf2ff2-cbf1-41cd-bec8-fe782b0e8f7e
    is_shared: false
    name: s3_store_kfp
    type: artifact_store
    user: 40830475-ee22-4674-83d1-764e06bb802d
  container_registry:
    configuration:
      authentication_secret: null
      uri: <account_ID>.dkr.ecr.eu-west-1.amazonaws.com
    flavor: default
    id: 7d28be65-96ed-4149-8210-44aaa8a3f31f
    is_shared: false
    name: ecr_registry_kfp
    type: container_registry
    user: 40830475-ee22-4674-83d1-764e06bb802d
  orchestrator:
    configuration:
      kubeflow_hostname: null
      kubeflow_namespace: kubeflow
      kubeflow_pipelines_ui_port: 8080
      kubernetes_context: k8scluster
      skip_cluster_provisioning: true
      skip_local_validations: true
      skip_ui_daemon_provisioning: false
      synchronous: false
    flavor: kubeflow
    id: c924bf76-e6a8-4a0e-a117-46475cf559f7
    is_shared: false
    name: kfp_orchestrator
    type: orchestrator
    user: 40830475-ee22-4674-83d1-764e06bb802d
stack_name: kfp_stack
zenml_version: 0.21.0
```

2. Import the stack
```
$ zenml stack import kfp_stack -f kfp_stack.yaml
```

3. List the stack
```
$ zenml stack list
Unable to find ZenML repository in your current working directory (/workspaces/preparation-time-correction-implement-training) or any parent directories. If you want to use an existing repository which is in a different location, set the environment variable 'ZENML_REPOSITORY_PATH'. If you want to create a new repository, run zenml init.
Running without an active repository root.
Using the default local database.
Running with active project: 'default' (global)

┏━━━━━━━━┯━━━━━━━━━━━━━━━━┯━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┯━━━━━━━━┯━━━━━━━━━┯━━━━━━━━━━━━━━━━━━┯━━━━━━━━━━━━━━━━━━━━┯━━━━━━━━━━━━━━━━┓
┃ ACTIVE │ STACK NAME     │ STACK ID                        │ SHARED │ OWNER   │ ORCHESTRATOR     │ CONTAINER_REGISTRY │ ARTIFACT_STORE ┃
┠────────┼────────────────┼─────────────────────────────────┼────────┼─────────┼──────────────────┼────────────────────┼────────────────┨
┃   👉   │ kfp_stack      │ 710732b7-2946-48ce-a484-b3baa3a │ ➖     │ default │ kfp_orchestrator │ ecr_registry_kfp   │ s3_store_kfp   ┃
┃        │                │ f1cbf                           │        │         │                  │                    │                ┃
┗━━━━━━━━┷━━━━━━━━━━━━━━━━┷━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┷━━━━━━━━┷━━━━━━━━━┷━━━━━━━━━━━━━━━━━━┷━━━━━━━━━━━━━━━━━━━━┷━━━━━━━━━━━━━━━━┛
```

4. Set and run the stack
```
$ zenml stack set kfp_stack
$ zenml stack up
```

5. Run the pipeline and observe the first pod that comes up from the first step.
...

### Relevant log output

```shell
time="2022-10-31T11:41:24.673Z" level=info msg="capturing logs" argo=true
[33mUnable to find ZenML repository in your current working directory (/app) or any parent directories. If you want to use an existing repository which is in a different location, set the environment variable 'ZENML_REPOSITORY_PATH'. If you want to create a new repository, run [0m[33mzenml init[33m.[0m
[1;35mRunning without an active repository root.[0m
[1;35mCreating default project 'default' ...[0m
[1;35mCreating default user 'default' ...[0m
[1;35mCreating default stack for user 'default' in project default...[0m
[33mThe current global active stack is no longer available. Resetting the active stack to default.[0m
[1;35mUsing the default store for the global config.[0m
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /usr/local/lib/python3.9/runpy.py:197 in _run_module_as_main                 │
│                                                                              │
│   194 │   main_globals = sys.modules["__main__"].__dict__                    │
│   195 │   if alter_argv:                                                     │
│   196 │   │   sys.argv[0] = mod_spec.origin                                  │
│ ❱ 197 │   return _run_code(code, main_globals, None,                         │
│   198 │   │   │   │   │    "__main__", mod_spec)                             │
│   199                                                                        │
│   200 def run_module(mod_name, init_globals=None,                            │
│                                                                              │
│ /usr/local/lib/python3.9/runpy.py:87 in _run_code                            │
│                                                                              │
│    84 │   │   │   │   │      __loader__ = loader,                            │
│    85 │   │   │   │   │      __package__ = pkg_name,                         │
│    86 │   │   │   │   │      __spec__ = mod_spec)                            │
│ ❱  87 │   exec(code, run_globals)                                            │
│    88 │   return run_globals                                                 │
│    89                                                                        │
│    90 def _run_module_code(code, init_globals=None,                          │
│                                                                              │
│ /usr/local/lib/python3.9/site-packages/zenml/entrypoints/entrypoint.py:58 in │
│ <module>                                                                     │
│                                                                              │
│   55                                                                         │
│   56                                                                         │
│   57 if __name__ == "__main__":                                              │
│ ❱ 58 │   main()                                                              │
│   59                                                                         │
│                                                                              │
│ /usr/local/lib/python3.9/site-packages/zenml/entrypoints/entrypoint.py:54 in │
│ main                                                                         │
│                                                                              │
│   51 │   )                                                                   │
│   52 │   entrypoint_config = entrypoint_config_class(arguments=remaining_arg │
│   53 │                                                                       │
│ ❱ 54 │   entrypoint_config.run()                                             │
│   55                                                                         │
│   56                                                                         │
│   57 if __name__ == "__main__":                                              │
│                                                                              │
│ /usr/local/lib/python3.9/site-packages/zenml/entrypoints/step_entrypoint_con │
│ figuration.py:167 in run                                                     │
│                                                                              │
│   164 │   │                                                                  │
│   165 │   │   step = deployment_config.steps[step_name]                      │
│   166 │   │   entrypoint_utils.load_and_configure_step(step)                 │
│ ❱ 167 │   │   execution_info = self._run_step(step, deployment=deployment_co │
│   168 │   │                                                                  │
│   169 │   │   self.post_run(                                                 │
│   170 │   │   │   pipeline_name=pipeline_name,                               │
│                                                                              │
│ /usr/local/lib/python3.9/site-packages/zenml/entrypoints/step_entrypoint_con │
│ figuration.py:189 in _run_step                                               │
│                                                                              │
│   186 │   │   Returns:                                                       │
│   187 │   │   │   Optional execution info of the run.                        │
│   188 │   │   """                                                            │
│ ❱ 189 │   │   orchestrator = Client().active_stack.orchestrator              │
│   190 │   │   orchestrator._prepare_run(deployment=deployment)               │
│   191 │   │   return orchestrator.run_step(step=step)                        │
│   192                                                                        │
│                                                                              │
│ /usr/local/lib/python3.9/site-packages/zenml/client.py:645 in active_stack   │
│                                                                              │
│    642 │   │   """                                                           │
│    643 │   │   from zenml.stack.stack import Stack                           │
│    644 │   │                                                                 │
│ ❱  645 │   │   return Stack.from_model(self.active_stack_model)              │
│    646 │                                                                     │
│    647 │   @track(event=AnalyticsEvent.SET_STACK)                            │
│    648 │   def activate_stack(self, stack: "StackModel") -> None:            │
│                                                                              │
│ /usr/local/lib/python3.9/site-packages/zenml/client.py:634 in                │
│ active_stack_model                                                           │
│                                                                              │
│    631 │   │   │   │   "`zenml stack set STACK_NAME` to set the active stack │
│    632 │   │   │   )                                                         │
│    633 │   │                                                                 │
│ ❱  634 │   │   return self.zen_store.get_stack(stack_id=stack_id).to_hydrate │
│    635 │                                                                     │
│    636 │   @property                                                         │
│    637 │   def active_stack(self) -> "Stack":                                │
│                                                                              │
│ /usr/local/lib/python3.9/site-packages/zenml/zen_stores/sql_zen_store.py:674 │
│ in get_stack                                                                 │
│                                                                              │
│    671 │   │   │   ).first()                                                 │
│    672 │   │   │                                                             │
│    673 │   │   │   if stack is None:                                         │
│ ❱  674 │   │   │   │   raise KeyError(f"Stack with ID {stack_id} not found." │
│    675 │   │   │   return stack.to_model()                                   │
│    676 │                                                                     │
│    677 │   def list_stacks(                                                  │
╰──────────────────────────────────────────────────────────────────────────────╯
KeyError: 'Stack with ID 710732b7-2946-48ce-a484-b3baa3af1cbf not found.'
time="2022-10-31T11:41:32.220Z" level=info msg="no need to save artifact - on overlapping volume: /outputs/mlpipeline-ui-metadata.json" argo=true
Error: exit status 1
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
